name: Setup
description: 'Setup ComfyUI frontend'
inputs:
  extra_server_params:
    description: 'Additional parameters to pass to ComfyUI server'
    required: false
    default: ''
  devtools_ref:
    description: 'Reference to use for ComfyUI_devtools'
    required: false
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Checkout ComfyUI
      uses: actions/checkout@v4
      with:
        repository: 'comfyanonymous/ComfyUI'
        path: 'ComfyUI'
        ref: master
    - name: Checkout ComfyUI_frontend
      uses: actions/checkout@v4
      with:
        repository: 'Comfy-Org/ComfyUI_frontend'
        path: 'ComfyUI_frontend'
    - name: Checkout ComfyUI_devtools
      uses: actions/checkout@v4
      with:
        repository: 'Comfy-Org/ComfyUI_devtools'
        path: 'ComfyUI/custom_nodes/ComfyUI_devtools'
        ref: ${{ inputs.devtools_ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        pip install wait-for-it
      shell: bash
      working-directory: ComfyUI
    - name: Build & Install ComfyUI_frontend
      run: |
        npm ci
        npm run build
        rm -rf ../ComfyUI/web/*
        mv dist/* ../ComfyUI/web/
      shell: bash
      working-directory: ComfyUI_frontend
    - name: Start ComfyUI server
      run: |
        python main.py --cpu --multi-user ${{ inputs.extra_params }} &
        wait-for-it --service 127.0.0.1:8188 -t 600
      working-directory: ComfyUI
      shell: bash
